WITH FE AS (
    SELECT SUM(CODE) CODE
    FROM SKILLCODES
    WHERE CATEGORY = "Front End"
)
   , C AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = "C#"
)
   , PYTHON AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = "Python"
), DEVELOPER_GRADE AS (
    SELECT
        CASE
            WHEN a.SKILL_CODE & b.CODE != 0 AND a.SKILL_CODE & d.CODE != 0 THEN 'A'
    WHEN a.SKILL_CODE & c.CODE != 0 THEN 'B'
    WHEN a.SKILL_CODE & b.CODE != 0 THEN 'C'
END AS GRADE,
        a.ID, a.EMAIL
    FROM DEVELOPERS a, FE b, C c, Python d
)

SELECT GRADE, ID, EMAIL
FROM DEVELOPER_GRADE
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID