-- https://school.programmers.co.kr/learn/courses/30/lessons/301646
-- 특정 형질을 가지는 대장균 찾기

-- 방법 1. 비트연산 활용
-- 1)
SELECT COUNT(ID) AS COUNT
FROM ECOLI_DATA
WHERE (GENOTYPE & 2 != 2) AND (GENOTYPE & 1 = 1 OR GENOTYPE & 4 = 4)
-- 2)
SELECT COUNT(ID) AS COUNT
FROM ECOLI_DATA
WHERE (GENOTYPE & 2 != 2) AND (GENOTYPE & 5 > 5)

-- 방법 2. 2진수로 나타내기 
SELECT CONV(GENOTYPE, 10, 2) MOD 10 AS ONE,
       (CONV(GENOTYPE, 10, 2) MOD 100) DIV 10 AS TWO,
       (CONV(GENOTYPE, 10, 2) MOD 1000) DIV 100 AS THREE
FROM ECOLI_DATA

SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA E, 
     (SELECT CONV(GENOTYPE, 10, 2) MOD 10 AS ONE,
             (CONV(GENOTYPE, 10, 2) MOD 100) DIV 10 AS TWO,
             (CONV(GENOTYPE, 10, 2) MOD 1000) DIV 100 AS THREE,
              ID
      FROM ECOLI_DATA) G
WHERE E.ID = G.ID AND G.TWO = 0 AND (G.ONE = 1 OR G.THREE = 1);