-- https://school.programmers.co.kr/learn/courses/30/lessons/299310
-- year, year_dev, id
-- WITH 가상테이블 AS()

WITH MAX_COLONY AS(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MC
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(C.DIFFERENTIATION_DATE) AS YEAR, 
       M.MC-C.SIZE_OF_COLONY AS YEAR_DEV,
       C.ID
FROM ECOLI_DATA C
JOIN MAX_COLONY M
ON YEAR(C.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY M.YEAR, YEAR_DEV;
