SELECT
    fp.PRODUCT_ID
     ,fp.PRODUCT_NAME
     ,SUM(fp.PRICE*fo.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER fo
    INNER JOIN FOOD_PRODUCT fp
    ON fo.PRODUCT_ID = fp.PRODUCT_ID
WHERE fo.PRODUCE_DATE LIKE '2022-05%'
GROUP BY fp.PRODUCT_ID,fp.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC ,fp.PRODUCT_ID;