-- WHERE절 사용 코드
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I 
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE (I.FISH_TYPE, I.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AND I.FISH_TYPE = N.FISH_TYPE
ORDER BY I.ID;


-- OVER() 사용 코드
SELECT ID, FISHNAME, LENGTH
FROM (
    SELECT ID, FISHTYPE, LENGTH,
        RANK() OVER(PARTITION BY FISHTYPE ORDER BY LENGTH DESC) AS LENGTHRANK
    FROM FISHINFO
) AS INFO
JOIN FISHNAMEINFO AS NAME
ON NAME.FISHTYPE = INFO.FISHTYPE
WHERE LENGTHRANK = 1
ORDER BY ID;