-- https://school.programmers.co.kr/learn/courses/30/lessons/151141
-- 자동차 대여 기록 별 대여 금액 구하기
WITH CTE AS (
    SELECT HISTORY_ID, DAILY_FEE, DATEDIFF(END_DATE, START_DATE)+1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
    WHERE CAR_TYPE = '트럭'
)
SELECT HISTORY_ID, 
    CASE
    WHEN DURATION < 7 THEN DURATION * DAILY_FEE
    WHEN DURATION >= 7 AND DURATION < 30 
    THEN ROUND(DAILY_FEE * DURATION * 0.95, 0)
    WHEN DURATION >= 30 AND DURATION < 90
    THEN ROUND(DAILY_FEE * DURATION * 0.92, 0)
    WHEN DURATION >=90 THEN ROUND(DAILY_FEE * DURATION * 0.85, 0)
    END AS FEE
FROM CTE
ORDER BY FEE DESC, HISTORY_ID DESC