-- PERCENT_RANK() 사용
WITH RANK_TABLE AS (
    SELECT
        ID,
        PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) SIZE_RANK
    FROM
        ECOLI_DATA
)

SELECT
    ID,
    CASE
        WHEN SIZE_RANK <= 0.25 THEN 'CRITICAL'
        WHEN SIZE_RANK <= 0.50 THEN 'HIGH'
        WHEN SIZE_RANK <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END COLONY_NAME
FROM
    RANK_TABLE
ORDER BY
    ID;

-- NTILE(n) 사용
WITH RANK_TABLE AS (
    SELECT
        ID,
        NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) SIZE_RANK
    FROM
        ECOLI_DATA
)

SELECT
    ID,
    CASE
        WHEN SIZE_RANK = 1 THEN 'CRITICAL'
        WHEN SIZE_RANK = 2 THEN 'HIGH'
        WHEN SIZE_RANK = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END COLONY_NAME
FROM
    RANK_TABLE
ORDER BY
    ID;