SELECT a.MEMBER_NAME, b.REVIEW_TEXT, DATE_FORMAT(b.REVIEW_DATE, '%Y-%m-%d') `REVIEW_DATE`
FROM MEMBER_PROFILE a
         LEFT JOIN REST_REVIEW b ON a.MEMBER_ID = b.MEMBER_ID
WHERE a.MEMBER_ID IN (
    SELECT a2.MEMBER_ID
    FROM MEMBER_PROFILE a2
             LEFT JOIN REST_REVIEW b2 ON a2.MEMBER_ID = b2.MEMBER_ID
    GROUP BY a2.MEMBER_ID
    HAVING COUNT(a2.MEMBER_ID) = (
        SELECT MAX(REVIEW_COUNT)
        FROM (
                 SELECT COUNT(a2.MEMBER_ID) AS REVIEW_COUNT
                 FROM MEMBER_PROFILE a2
                          LEFT JOIN REST_REVIEW b2 ON a2.MEMBER_ID = b2.MEMBER_ID
                 GROUP BY a2.MEMBER_ID
             ) sub_query
    )
)

ORDER BY REVIEW_DATE, REVIEW_TEXT