-- 멸종위기의 대장균 찾기
-- https://school.programmers.co.kr/learn/courses/30/lessons/301651
WITH RECURSIVE GEN_DATA AS(
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, G.GENERATION+1
    FROM GEN_DATA G
    JOIN ECOLI_DATA E
    ON G.ID = E.PARENT_ID
)

SELECT COUNT(P.ID) AS COUNT, G.GENERATION
FROM ECOLI_DATA P
JOIN GEN_DATA G
ON P.ID = G.ID
LEFT JOIN ECOLI_DATA C
ON P.ID = C.PARENT_ID
WHERE C.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION