SELECT
    ch.HISTORY_ID,
    IF(DISCOUNT_RATE IS NULL,
       daily_fee * FEE,
       FLOOR((daily_fee * FEE)*(1-(DISCOUNT_RATE/100)))) FEE
FROM CAR_RENTAL_COMPANY_CAR cc
INNER JOIN (
    SELECT HISTORY_ID, CAR_ID, TIMESTAMPDIFF(DAY,START_DATE,END_DATE)+1 FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) ch
ON cc.CAR_ID = ch.CAR_ID
LEFT JOIN (
    SELECT SUBSTRING_INDEX(DURATION_TYPE,'일',1) DAY,
    SUBSTRING_INDEX(DISCOUNT_RATE,'%',1) DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) cp
ON (CASE
       WHEN ch.FEE BETWEEN 7 AND 30 THEN 7
       WHEN ch.FEE BETWEEN 30 AND 90 THEN 30
       WHEN ch.FEE >= 90 THEN 90
   END) = cp.DAY
WHERE cc.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;