WITH CTE AS (
    SELECT a.PRODUCT_ID, a.NEW_PRICE, a.CHANGE_DATE
    FROM PRODUCTS a
    WHERE (a.PRODUCT_ID, a.CHANGE_DATE) IN (
        SELECT PRODUCT_ID, MAX(CHANGE_DATE)
        FROM PRODUCTS
        WHERE CHANGE_DATE <= '2019-08-16'
        GROUP BY PRODUCT_ID
    )
), PRODUCT_ID_TABLE AS (
    SELECT DISTINCT a.PRODUCT_ID
    FROM PRODUCTS a
)

SELECT a.PRODUCT_ID `product_Id`, IFNULL(b.NEW_PRICE, 10) `price`
FROM PRODUCT_ID_TABLE a
LEFT JOIN CTE b ON a.PRODUCT_ID = b.PRODUCT_ID