-- Department Top Three Salaries
-- https://leetcode.com/problems/department-top-three-salaries/

-- 1) DESE_RANK() 활용
SELECT D.NAME AS Department, E.NAME AS Employee, E.SALARY AS Salary 
FROM (
    SELECT NAME, SALARY, DEPARTMENTID, DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RK
    FROM EMPLOYEE
) E
JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.ID
WHERE RK <= 3

-- 2) 서브쿼리 활용
SELECT D.NAME AS Department, E.NAME AS Employee, E.SALARY AS Salary 
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
WHERE (SELECT COUNT(DISTINCT SALARY)
        FROM EMPLOYEE CE
        WHERE E.DEPARTMENTID = CE.DEPARTMENTID AND CE.SALARY >= E.SALARY
    ) <= 3