WITH RECURSIVE TMP AS (
    (SELECT 0 HOUR)
    UNION ALL
    (SELECT HOUR + 1 FROM TMP WHERE HOUR < 23)
)

SELECT A.HOUR, IFNULL(B.COUNT, 0) `COUNT`
FROM TMP A LEFT JOIN (
    SELECT HOUR(DATETIME) `HOUR`, COUNT(HOUR(DATETIME)) `COUNT`
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) B ON A.HOUR = B.HOUR