-- 상품을 구매한 회원 비율 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131534
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
       , COUNT(DISTINCT B.USER_ID) AS PURCHASED_USERS
       , ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM USER_INFO A
JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
WHERE YEAR(JOINED) = 2021 AND PRODUCT_ID IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH