-- 코드를 입력하세요
-- 2022년 3월의 오프라인/온라인 상품 판매 데이터의 판매 날짜, 상품ID, 유저ID, 판매량 출력

-- 필터링 적용 후, UNION 진행
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM
    (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
     FROM ONLINE_SALE
     WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
     UNION ALL
     SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
     FROM OFFLINE_SALE
     WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
    ) A
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

-----
-- UNION 진행 후 필터링 진행
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM
    (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
     FROM ONLINE_SALE
     UNION ALL
     SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
     FROM OFFLINE_SALE
    ) A
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID