SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(b.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE m
         JOIN REST_REVIEW b
              ON m.MEMBER_ID = b.MEMBER_ID
WHERE b.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
    )
ORDER BY b.REVIEW_DATE ASC, b.REVIEW_TEXT;