WITH RECURSIVE TM AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 
    FROM TM 
    WHERE HOUR < 23
)

SELECT A.HOUR, IFNULL(B.COUNT, 0) AS COUNT
FROM TM A
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR,
           COUNT(HOUR(DATETIME)) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) B ON A.HOUR = B.HOUR