SELECT YEAR(a.SALES_DATE) `YEAR`
        , MONTH(a.SALES_DATE) `MONTH`
        , b.GENDER `GENDER`
        , COUNT(DISTINCT(b.USER_ID)) `USERS`
FROM ONLINE_SALE a
    JOIN USER_INFO b ON a.USER_ID = b.USER_ID
WHERE b.GENDER IS NOT NULL

GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
