WITH ColonyData AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        SIZE_OF_COLONY, 
        ID
    FROM ECOLI_DATA
),
MaxColony AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
           MAX(SIZE_OF_COLONY) AS MX
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT c.YEAR,
        (m.MX - c.SIZE_OF_COLONY) AS YEAR_DEV,
        c.ID
FROM ColonyData c
JOIN MaxColony m ON C.YEAR = M.YEAR
ORDER BY c.YEAR, YEAR_DEV;