(SELECT b.NAME `results`
 FROM MOVIERATING a LEFT JOIN USERS b ON a.USER_ID = b.USER_ID
 GROUP BY a.USER_ID
 ORDER BY COUNT(a.USER_ID) DESC, b.NAME ASC
     LIMIT 1)
UNION ALL
(SELECT b.title `results`
 FROM MOVIERATING a LEFT JOIN MOVIES b ON a.MOVIE_ID = b.MOVIE_ID
 WHERE CREATED_AT LIKE '2020-02-%'
 GROUP BY a.MOVIE_ID
 ORDER BY AVG(a.RATING) DESC, b.TITLE ASC
     LIMIT 1)