-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/157339

-- 1)'세단' or 'SUV'인 자동차 중, 
-- 2) 2022.11.01~2022.11.30까지 대여 가능하고
-- 3) 30일간 대여 금액이, 50만원 이상 200만원 미만인 자동차 출력
SELECT C.CAR_ID, C.CAR_TYPE,
       FLOOR(DAILY_FEE *(1-DISCOUNT_RATE*0.01) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID 
   AND START_DATE <= "2022-11-30"
   AND END_DATE >= "2022-11-01"
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE AND DURATION_TYPE = "30일 이상"
WHERE C.CAR_TYPE IN ("SUV", "세단") 
      AND START_DATE IS NULL
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC

