WITH TMP AS (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
    #   ROW_NUMBER(): 행 번호 표시
    #   PARTITION BY FOOD_TYPE: FOOD_TYPE 별로 순위를 나눔
    ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC, REST_ID) AS RANK_FAVOIRTES
    FROM REST_INFO
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM TMP
WHERE RANK_FAVOIRTES = 1
ORDER BY FOOD_TYPE DESC